# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [ ]:
import numpy as np
nuevo_array=np.zeros(12)
print(nuevo_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
array2=np.zeros(10)
array2[4]=10
print(array2)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [ ]:
import numpy as np
array3=np.arange(10,50)
print(array3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
import numpy as np
lista=[[0,1,2], [3,4,5],[6,7,8]]
array2d=np.array(lista)
print(array2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
import numpy as np
array_aleatorio=np.random.rand(100)
media= np.mean(array_aleatorio)
varianza=np.var(array_aleatorio)
print(varianza)

0.07627991129187037


In [ ]:
array=np.array ([1,2,3,4,5])
suma_total=np.sum(array)
numero_elementos=array.size
media= suma_total/numero_elementos
print(media)

3.0


In [ ]:
print(np.random.rand(20))

[0.21906424 0.08909975 0.6666615  0.3702751  0.04055804 0.64475489
 0.98967346 0.47349207 0.0859228  0.658887   0.0764031  0.91343726
 0.04758183 0.8941504  0.81456204 0.24311776 0.84904889 0.44701719
 0.30025347 0.06371915]
